version: '3.7'

services:
  backend:
    build: ./API/
    image: api
    command: python manage.py runserver 0.0.0.0:8000
    # volumes:
    #   - ./backend/
    ports:
      - 8000:8000
    
  frontend:
    build: ./vkr-ui/
    image: ui
    command: npm start
    ports:
      - 80:3000    
    depends_on:
      - backend