# Generated by Django 4.0.5 on 2022-06-14 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('location_name', models.CharField(default='default location', max_length=100, primary_key=True, serialize=False)),
                ('location_img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MarkerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker_img', models.ImageField(upload_to='')),
                ('marker_hash', models.CharField(max_length=255, null=True)),
                ('marker_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.locationmodel')),
            ],
        ),
    ]
