# Generated by Django 4.0.5 on 2022-06-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_imagemodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='location_img',
            field=models.ImageField(upload_to='images/locations'),
        ),
        migrations.AlterField(
            model_name='markermodel',
            name='marker_hash',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='markermodel',
            name='marker_img',
            field=models.ImageField(upload_to='images/markers'),
        ),
    ]
